### ISSUE TITLE
Problem with more than one encrypted folder

### ISSUE THREAD

**Issue by pucicu** [corelan/pyencfsgui#1]
I have tested now with two folders. When I mount one, the other one is then also marked as mounted, although it is not mounted. I cannot mount the second folder, when the first one is already mounted. And it doesn't depent on the order which folder was mounted first.

**Comment by corelanc0d3r** [comment]
can you please try again with the very latest version?  if the issue isn't fixed after commit https://github.com/corelan/pyencfsgui/commit/be8f3e22c7a715be4b570e1883083a36992eb9dd,  can you please share the contents of your encfsgui.volumes file? thanks!

**Comment by pucicu** [comment]
thanks!
now it is another issue. after mounting folder A, and then mounting folder B, folder A gets unmounted and folder B is mounted. but in the GUI both folders appear to be mounted (what is physically not true).


```
[Boxcryptor]
enc_path = /Users/m…/MEGA/.encrypted/BoxCryptor.bc
mount_path = /Users/m…/Volumes/BoxCryptor
automount = 1
preventautounmount = 1
allowother = 0
mountaslocal = 1
encfsmountoptions = 
passwordsaved = 1

[Betriebsrat]
enc_path = /Users/m…/Documents/Betriebsrat.bc
mount_path = /Users/m…/Volumes
automount = 1
preventautounmount = 1
allowother = 0
mountaslocal = 1
encfsmountoptions = 
passwordsaved = 1

```

**Comment by corelanc0d3r** [comment]
interesting - not sure if the above listing is accurate, but if I understand correctly, the first volume is in fact being mounted as a subfolder of the second one ?

```
Second mount_path : mount_path = /Users/m…/Volumes
First mount_path: /Users/m…/Volumes/BoxCryptor
```
If that is the case indeed, can you try to mount them in their own folder side by side, instead of inside each other?

**Comment by pucicu** [comment]
sorry, this was indeed my mistake. it was not intended to have it as a subfolder. i have corrected it and it is now working as expected. thanks for your great work!

**Comment by corelanc0d3r** [comment]
awesome, thanks ! :)
