### ISSUE TITLE
Installing dependencies on macOS: issue with osxfuse/macfuse

### ISSUE THREAD

**Issue by scottmeup** [corelan/pyencfsgui#2]
`brew install encfs` and `brew install gocryptfs` as listed under Installing dependencies on macOS, no longer work. 

Using macfuse as a cask dependency seems to be unsupported according to this discussion https://github.com/Homebrew/discussions/discussions/1250

**Comment by corelanc0d3r** [comment]
perhaps this should be reported to the encfs / gocryptfs guys as well?

**Comment by corelanc0d3r** [comment]
Found these 2 issues for encfs:
https://github.com/vgough/encfs/issues/630 
https://github.com/vgough/encfs/issues/629 

Just wondering: have you tried installing macFUSE using the dmg from https://osxfuse.github.io/?

**Comment by scottmeup** [comment]
Hi, thanks for the reply. I have installed the package from https://osxfuse.github.io/

If I understand correctly, the brew recipes for encfs & gocryptfs have been disabled regardless of whether macfuse / osxfuse is installed.

**Comment by corelanc0d3r** [comment]
ah yes, not sure why they have disabled the recipes... I guess someone will come up with a solution 
I'll close the issue here (as it is not a pyencfsgui issue)

**Comment by scottmeup** [comment]
Awesome, just thought it might be useful info as the readme mentions those methods for installing dependencies on macOS.
Cheers ;)

**Comment by corelanc0d3r** [comment]
True, I'll add a note, but I guess we'll have to wait for them to come up a solution

**Comment by scottmeup** [comment]
Yeah, definitely. Macports offers encfs, unfortunately I didn't see a gocryptfs port.

**Comment by corelanc0d3r** [comment]
ah good to know - have you tried installing via macports? did it work?
do you happen to have the instructions, so I can put them in the readme?
thanks!

**Comment by scottmeup** [comment]
encfs via macports works fine for me, ymmv; it looks like it doesn't build on all major releases of macOS according to the port page https://ports.macports.org/port/encfs/builds

Macports' install instructions & package download are available here https://www.macports.org/install.php

Once you've run through those instructions it's recommended to update macports with `sudo port selfupdate`, then you can install enfcs with `sudo port install encfs`

As for gocryptfs, people might just have to compile it themselves.
